### ISSUE TITLE
Index Template Mapping for smtp.date may be incorrect

### ISSUE THREAD

**Issue by akusei** [corelight/ecs-templates#21]
The index template mapping in `corelight-ds-component_template-main_logs-mappings` on line 3126 has a mapping for `smtp.date` which is defined as data type `date`. The data being added to that field is not in any built-in date format that Elasticsearch will parse. I've tried to add a custom formatter which worked for a bit but it looks like the dates in that field are very different and it should probably be a keyword or text field instead of a date field.

Some examples values I've seen which have caused documents to fail indexing:
```
Thu Jun  8 23:32:39 2023
Thu, 08 Jun 2023 20:48:27 +0000
Thu,  8 Jun 2023 20:48:27 -0700 (PDT)
```

I'm sure there's more but those are the most recent. Every time I adjust the ingest pipeline with a new custom format, it changes. I don't think the index template should have defined this field as a date. If the data type is meant to be date, the ingest pipeline needs to be fixed so it properly parses all possible deviations of values that could be provided as timestamps

**Comment by hunter32me** [comment]
I will take a look at this and update the pipeline as needed

**Comment by hunter32me** [comment]
Ok looking through RFC 2822 the the first one is not in the correct order should be day of week day month (three letters) years then time with a offset from GMT. We could normalized the bottom two look to be space delimited. Will runinto the same problem with the non compliant date stamps you run into now. Could also change the field to TXT/Keyword. WIll look into this more
