### ISSUE TITLE
Ingest Pipelines do not get added to the index templates with the installer

### ISSUE THREAD

**Issue by mick-lue** [corelight/ecs-templates#31]
Hello,

I was troubleshooting an error where we could not get the corelight data ecs compliant even though we followed the basic installer routine and set the necessary options in the software scanner.

It turned out that the component template for the ingest pipelines is not getting added to the index templates. After manually adding it, the expected transformations for ecs-compliance were performed.
I justed used the default settings for the installer, except for entering 'i' when asked for the pipeline of course.
Is this a bug or did I miss any steps along the way?

**Comment by hunter32me** [comment]
There was an error we fixed yesterday that caused the script to download the wrong repro from ingest. This was push yesterday. Now to get data from Corelight to ECS you will need to set the index prefix to temporary_corelight_routing_index this will cause trigger the index template and the correct component template to run the ingest pipelines

**Comment by mick-lue** [comment]
Oh I see, thanks for the clarification! Seems like I did miss something along the way. It works now, so I am closing this issue.
